mapping = {
    "root": {
        "//[ The tag for each page in the xml file tree ]//": "",
        "tag": "item",
        "//[ The page type in xml tag <wp:post_type> ]//": "",
        "type": "page",
        "//[ The statuses to import ]//": "",
        "status": ["publish", "draft"],
    },
    "item": {
        "title": "title",
        "link": [],
        "pubDate": [],
        "dc:creator": [],
        "guid": [],
        "description": [],
        "content:encoded": "body",
        "excerpt:encoded": [],
        "wp:post_id": ["wp_post_id"],
        "wp:post_date": [],
        "wp:post_date_gmt": ["%%date", "first_published_at"],
        "wp:post_modified": [],
        "wp:post_modified_gmt": [
            "%%date",
            "last_published_at:latest_revision_created_at",
        ],
        "wp:comment_status": [],
        "wp:ping_status": [],
        "wp:post_name": ["slug", "*slugify", "required"],
        "wp:status": ["__status"],
        "wp:post_parent": [],
        "wp:menu_order": [],
        "wp:post_type": ["wp_post_type"],
        "wp:post_password": [],
        "wp:is_sticky": [],
        "wp:postmeta": [],
        "wp:postmeta/wp:meta_key": [],
        "wp:postmeta/wp:meta_value": [],
        "category": [],
        "content:encoded/strong": [],
        "content:encoded/a": [],
        "content:encoded/strong/a": [],
        "content:encoded/strong/a/em": [],
        "content:encoded/blockquote": [],
        "content:encoded/blockquote/strong": [],
        "content:encoded/ul": [],
        "content:encoded/ul/li": [],
        "content:encoded/ul/li/a": [],
        "content:encoded/span": [],
        "content:encoded/span/strong": [],
    },
}
