HTML_TAGS = {
    "address": "block",
    "article": "block",
    "aside": "block",
    "blockquote": "block",
    "canvas": "block",
    "dd": "block",
    "div": "block",
    "dl": "block",
    "dt": "block",
    "fieldset": "block",
    "figcaption": "block",
    "figure": "block",
    "footer": "block",
    "form": "block",
    "h1": "block",
    "h2": "block",
    "h3": "block",
    "h4": "block",
    "h5": "block",
    "h6": "block",
    "header": "block",
    "hr": "block",
    "li": "block",
    "main": "block",
    "nav": "block",
    "noscript": "block",
    "ol": "block",
    "p": "block",
    "pre": "block",
    "section": "block",
    "table": "block",
    "tfoot": "block",
    "ul": "block",
    "video": "block",
    "a": "inline",
    "abbr": "inline",
    "acronym": "inline",
    "b": "inline",
    "bdo": "inline",
    "big": "inline",
    "br": "inline",
    "button": "inline",
    "center": "inline", # not stricty allowed but here for later styling
    "cite": "inline",
    "code": "inline",
    "dfn": "inline",
    "em": "inline",
    "i": "inline",
    "img": "inline",
    "input": "inline",
    "kbd": "inline",
    "label": "inline",
    "map": "inline",
    "object": "inline",
    "output": "inline",
    "q": "inline",
    "samp": "inline",
    "script": "inline",
    "select": "inline",
    "small": "inline",
    "span": "inline",
    "strong": "inline",
    "sub": "inline",
    "sup": "inline",
    "textarea": "inline",
    "time": "inline",
    "tt": "inline",
    "var": "inline",
}

FILTER_MAPPING = {
    "bold": [
        # output content in <b></b>
        "color: rgb(0, 0, 153); font-weight: bold;",
        "color: rgb(0, 102, 0); font-weight: bold;",
        "color: rgb(204, 0, 0); font-weight: bold;",
        "font-style: italic; font-weight: bold;",
        "FONT-WEIGHT: bold",
        "font-weight: bold;",
        "font-weight: bold; color: #006600;",
        "font-weight: bold; color: #990000;",
        "font-weight: bold; color: #cc0000;",
        "font-weight: bold; color: #cc0000; font-style: italic;",
        "font-weight: bold; color: #ff0000;",
        "font-weight: bold; color: rgb(0, 102, 0);",
        "font-weight: bold; color: rgb(153, 0, 0);",
        "font-weight: bold; color: rgb(153, 0, 0); font-style: italic;",
        "font-weight: bold; color: rgb(204, 0, 0);",
        "font-weight: bold; color: rgb(204, 0, 0); font-style: italic;",
        "font-weight: bold; font-size: 100%;",
        "font-weight: bold; font-size: 130%;",
        "font-weight: bold; font-size: 180%;",
        "font-weight: bold; font-style: italic;",
        "font-weight: bold; font-style: italic; color: #990000;",
        "font-weight: bold; font-style: italic; color: rgb(153, 0, 0);",
        "font-weight: bold;font-size:100%;",
        "font-weight: bold;font-size:130%;",
        "FONT-WEIGHT: bold;font-size:130%;",
        "FONT-WEIGHT: bold;font-size:180%;",
        "font-weight: bold;font-size:180%;",
    ],
    "italic": [
        # output content in <i> tag
        "color: #990000; font-style: italic;",
        "color: rgb(0, 0, 0); font-style: italic;",
        "color: rgb(102, 0, 0); font-style: italic;",
        "FONT-STYLE: italic",
        "font-style: italic;",
        "font-style: italic; color: #990000;",
        "font-style: italic; color: #ffff00;",
        "font-style: italic; color: rgb(153, 0, 0);",
        "font-style: italic; color: rgb(204, 0, 0);",
        "font-style: italic; color: rgb(255, 255, 0);",
        "font-style: italic; font-size: 100%;",
        "font-style: italic; font-size: 85%;",
        "font-style: italic;font-size:100%;",
        "font-style: italic;font-size:130%;",
        "font-style: italic;font-size:85%;",
    ],
    "bold-italic": [
        "font-style: italic; font-weight: bold;",
        "font-weight: bold; font-style: italic;",
    ],
    "center": [
        # add class `align-center`
        "DISPLAY: block; MARGIN: 0px auto 10px; WIDTH: 360px; CURSOR: pointer; TEXT-ALIGN: center",
        "display: block; margin: 0px auto 10px; width: 360px; cursor: pointer; text-align: center;",
        "font-size: 20px; text-align: center;",
        "margin-top: -5px; padding-bottom: 5px; text-align: center;",
        "margin: 0px auto 10px; display: block; width: 360px; cursor: pointer; text-align: center;",
        "margin: 0px auto 10px; width: 360px; text-align: center;",
        "padding-bottom: 20px; text-align: center;",
        "padding-top: 10px; padding-bottom: 20px; text-align: center;",
        "padding-top: 20px; text-align: center;",
        "TEXT-ALIGN: center",
        "text-align: center",
        "text-align: center;",
        "text-align: center; font-size: 16px;",
        "text-align: center; margin-bottom:10px;",
        "text-align: center; margin-top: -10px;",
        "text-align: center; margin-top: -10px; padding-bottom: 5px;",
        "text-align: center; margin-top: -12px;",
        "text-align: center; margin-top: -5px;",
        "text-align: center; margin-top: -5px; padding-bottom: 10px;",
        "text-align: center; margin-top: 30px;",
        "text-align: center; margin-top: 30px; padding-bottom: 10px;",
        "text-align: center; margin-top: 40px;",
        "text-align: center; margin-top:-20px;",
        "text-align: center; padding-bottom: 10px;",
        "text-align: center; padding-bottom: 5px;",
        "text-align: center; padding-top: 10px;",
        "text-align: center; padding-top: 10px; padding-bottom: 10px;",
        "text-align: center; padding-top: 15px;",
        "text-align: center; padding-top: 15px; padding-bottom: 20px;",
        "text-align: center; padding-top: 20px;",
        "text-align: center; padding-top: 20px; padding-bottom: 20px;",
        "text-align: center; padding-top: 30px;",
        "text-align: center; padding-top: 5px;",
        "text-align: center; text-decoration: underline;",
        "width: 22%; text-align: center;",
    ],
    "leftfloat": [
        # add class `float-left`
        "float: left; margin: 0em 1em 1em 0em;",
        "float: left; margin: 0pt 10px 0px 0pt; cursor: pointer;",
        "FLOAT: left; MARGIN: 0pt 10px 10px 0pt",
        "float: left; margin: 0pt 10px 10px 0pt;",
        "FLOAT: left; MARGIN: 0pt 10px 10px 0pt; CURSOR: pointer",
        "float: left; margin: 0pt 10px 10px 0pt; cursor: pointer;",
        "float: left; margin: 0pt 10px 10px 0pt; width: 166px; cursor: pointer;",
        "float: left; margin: 0pt 10px 10px 0pt; width: 194px; cursor: pointer;",
        "FLOAT: left; MARGIN: 0pt 10px 10px 0pt; WIDTH: 200px; CURSOR: pointer",
        "float: left; margin: 0pt 10px 10px 0pt; width: 235px; cursor: pointer;",
        "FLOAT: left; MARGIN: 0pt 10px 10px 0pt; WIDTH: 252px; CURSOR: pointer",
        "FLOAT: left; MARGIN: 0pt 10px 10px 0pt; WIDTH: 300px; CURSOR: pointer",
        "FLOAT: left; MARGIN: 0pt 10px 10px 0pt; WIDTH: 360px; CURSOR: pointer",
        "float: left; margin: 0pt 10px 10px 0pt; width: 376px; cursor: pointer;",
        "FLOAT: left; MARGIN: 0pt 10px 5px 0pt; CURSOR: pointer",
        "FLOAT: left; MARGIN: 0px 10px 10px 0px",
        "float: left; margin: 0px 10px 10px 0px;",
        "FLOAT: left; MARGIN: 0px 10px 10px 0px; CURSOR: hand",
        "float: left; margin: 0px 10px 10px 0px; cursor: hand;",
        "FLOAT: left; MARGIN: 0px 10px 10px 0px; WIDTH: 300px; alt:",
        "margin: 0pt 10px 0px 0pt; float: left;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer; width: 164px; height: 215px;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer; width: 170px; height: 162px;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer; width: 187px; height: 151px;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer; width: 200px; height: 155px;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer; width: 216px; height: 117px;",
        "margin: 0pt 10px 0px 0pt; float: left; cursor: pointer; width: 250px; height: 179px;",
        "margin: 0pt 10px 0px 0pt;float: left",
        "margin: 0pt 10px 10px 0pt; float: left;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 180px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 193px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 200px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 217px; height: 121px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 221px; height: 123px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 234px; height: 189px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 243px; height: 196px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 256px;",
        "margin: 0pt 10px 10px 0pt; float: left; cursor: pointer; width: 376px;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 150px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 214px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 215px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 256px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 288px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 324px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt; float: left; width: 376px; cursor: pointer;",
        "margin: 0pt 10px 10px 0pt;float: left",
        "margin: 0pt 10px 2px 0pt; float: left;",
        "margin: 0pt 10px 2px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 10px 4px 0pt; float: left;",
        "margin: 0pt 10px 4px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 10px 5px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 10px 6px 0pt; float: left;",
        "margin: 0pt 10px 6px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 10px 8px 0pt; float: left; cursor: pointer;",
        "margin: 0pt 15px 10px 0pt; float: left;",
        "margin: 0pt 8px 4px 0pt; float: left;",
        "margin: 0px 10px 0px 0px; float: left;",
        "margin: 0px 10px 10px 0px; float: left;",
        "margin: 0px 10px 10px 0px; float: left; width: 81px; height: 200px;",
        "margin: 0px 10px 6px 0px; float: left;",
        "margin: 20pt 0px 20px 10pt; float: left;",
    ],
    "rightfloat": [
        # add class `float-right`
        "float: right; margin: .5em 0em 1em 1em;",
        "float: right; margin: 0em 0em 0em 1em;",
        "margin: 0px 0px 0px 10px; float: right;",
        "margin: 0px 0px 10px 10px; float: right;",
        "margin: 0px 10px 10px 0px; float: right;",
        "margin: 5px 0px 0px 10px; float: right;",
    ],
    "remove": [
        # remove style tag completely
        "font-weight: 400;",
        "font-weight: normal;",
    ],
}

ALLOWED_TAGS = [
    "a",
    "abbr",
    "acronym",
    "aside",
    "b",
    "blockquote",
    "br",
    "button",
    "caption",
    "center", # not stictly allowed but we convert id later to css on a div
    "code",
    "col",
    "colgroup",
    "del",
    "div",
    "em",
    "footer",
    "form",
    "figure",
    "figcaption",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "hr",
    "i",
    "iframe",
    "img",
    "input",
    "label",
    "li",
    "ol",
    "option",
    "p",
    "s",
    "script",
    "select",
    "small",
    "span",
    "strike",
    "strong",
    "style",
    "sup",
    "table",
    "tbody",
    "td",
    "th",
    "thead",
    "time",
    "tr",
    "u",
    "ul",
    "wbr",
]

ALLOWED_ATTRIBUTES = {
    "*": ["class", "style", "id"],
    "a": [
        "aria-label",
        "data-wplink-edit",
        "href",
        "rel",
        "target",
        "title",
        "data-uw-rm-brl",
        "data-saferedirecturl",
        "name",
    ],
    "abbr": ["title"],
    "acronym": ["title"],
    "blockquote": [
        "data-cards",
        "data-lang",
        "data-instgrm-permalink",
        "data-instgrm-version",
        "data-instgrm-captioned",
    ],
    "button": ["data-target", "data-toggle"],
    "col": ["width"],
    "div": [
        "title",
        "data-campaign",
        "data-widget-id",
        "data-offer-id",
        "data-aff-id",
        "data-sub-id",
        "data-color",
        "role",
        "data-mm-rates",
    ],
    "form": ["action", "name", "method", "accept-charset"],
    "h2": ["big", "data-toctitle", "data-tocskip", "data-toskip", "data-toc-title"],
    "h3": ["data-toctitle", "data-tocskip"],
    "i": [
        "aria-hidden",
        "data-toggle",
        "data-placement",
        "title",
        "data-original-title",
    ],
    "iframe": [
        "allowfullscreen",
        "src",
        "width",
        "height",
        "frameborder",
        "scrolling",
        "marginwidth",
        "marginheight",
        "data-mce-fragment",
        "data-name",
        "data-link",
    ],
    "img": [
        "alt",
        "border",
        "data-src",
        "height",
        "sizes",
        "src",
        "srcset",
        "title",
        "width",
    ],
    "input": [
        "name",
        "placeholder",
        "readonly",
        "required",
        "type",
        "min",
        "max",
        "step",
        "value",
        "data-type",
    ],
    "label": ["for"],
    "li": ["aria-level", "value", "data-uw-node-idx"],
    "ol": ["data-mm-title", "start"],
    "option": ["data-desc", "data-option", "value", "selected"],
    "p": ["dir", "lang", "data-tocskip", "data-toctitle", "data-mm-rates"],
    "script": ["async", "charset", "defer", "src", "type"],
    "select": ["name"],
    "span": ["aria-invalid", "data-reactid", "data-preserver-spaces", "data-mm-rates"],
    "style": ["*"],
    "table": ["width", "dir", "border", "cellspacing", "cellpadding", "summary"],
    "tbody": ["data-mm-rates"],
    "td": [
        "data-label",
        "width",
        "colspan",
        "data-sheets-value",
        "data-sheets-numberformat",
        "data-sheets-formula",
        "data-sheets-hyperlink",
        "rowspan",
    ],
    "th": ["width", "scope", "colspan", "rowspan"],
    "time": ["datetime"],
    "ul": ["data-mm-title", "data-mm-rates"],
}

ALLOWED_STYLES = [
    # "border-top: 1px solid #E3DFD6; padding-top: 5px;",
    # "border: 1px solid #CCCCCC;",
    # "color",
    # "float: left; margin: 0em 1em 1em 0em;",
    "font-size",
    # "font-size: 18px;",
    # "font-size:130%;",
    # "font-size:85%;",
    "font-weight",
    # "font-weight: bold;",
    "font-style: italic;",
    "font-style",
    # "height: 702px;",
    # "line-height: 2.0;",
    # "margin-bottom: -5px;",
    # "margin-left: 244px; margin-right: 25px;",
    # "margin-top: -10px;",
    # "margin-top: -10px; padding-top: 20px;",
    # "margin-top: -20px; margin-bottom: 0px;",
    # "margin-top: -5px;",
    # "margin-top: -5px; padding-bottom: 10px;",
    # "margin-top: -5px; padding-bottom: 15px;",
    # "margin-top: -5px; padding-bottom: 5px;",
    # "margin-top: -5px; padding-bottom: 5px; text-align: center;",
    # "margin-top: -8px;",
    # "margin-top: 25px;",
    # "margin-top: 30px;",
    # "margin-top: 5px;",
    # "margin-top:-5px; padding-bottom:5px;",
    # "margin: 0pt 10px 10px 0pt;float: none",
    # "padding-bottom: 10px;",
    # "padding-bottom: 15px;",
    # "padding-bottom: 15px; padding-top: 15px;",
    # "padding-bottom: 1px; padding-top: 25px;",
    # "padding-bottom: 20px",
    # "padding-bottom: 20px;",
    # "padding-bottom: 2px;",
    # "padding-bottom: 4px;",
    # "padding-bottom: 5px;",
    # "padding-bottom: 7px;",
    # "padding-left: 30px;",
    # "padding-top 25px; padding-bottom: 25px;",
    # "padding-top: 10px;",
    # "padding-top: 10px; padding-bottom: 10px;",
    # "padding-top: 10px; padding-bottom: 20px;",
    # "padding-top: 15px;",
    # "padding-top: 18px;",
    # "padding-top: 20px;",
    # "padding-top: 30px; padding-bottom: 30px;",
    # "padding-top: 5px; padding-bottom: 10px;",
    # "TEXT-ALIGN: center",
    "text-align: center",
    "text-align: center;",
    # "text-align: center; font-size: 16px;",
    # "text-align: center; margin-top: -10px;",
    # "text-align: center; margin-top: -10px; padding-bottom: 5px;",
    # "text-align: center; margin-top: -12px;",
    # "text-align: center; margin-top: 40px;",
    # "text-align: center; padding-bottom: 10px;",
    # "text-align: center; padding-bottom: 5px;",
    # "text-align: center; padding-top: 10px; padding-bottom: 10px;",
    # "text-align: center; padding-top: 15px;",
    # "text-align: center; padding-top: 15px; padding-bottom: 20px;",
    # "text-align: center; padding-top: 20px;",
    # "text-align: center; padding-top: 20px; padding-bottom: 20px;",
    # "text-align: center; padding-top: 30px;",
    # "text-align: left;",
    # "width: 560px; height: 220px;",
    # "width: 560px; padding: 8px; background: #EEEEEE; border: 2px solid gray; margin: 0px;",
]
